all:
  children:
    proxmox:
      hosts:
        Aesir:
          ansible_host: 192.168.0.5
          ansible_user: root
          connectx: true
          intel_sriov: true
          zfsiscsi: true
          linstor: true
          linstor_controller: true
        # Possibly decom?
        # Vanir:
        #  ansible_host: 192.168.0.6
        #  ansible_user: root
        #  connectx: true
        #  zfsiscsi: true
        #  linstor: true
        Olympian:
          ansible_host: 192.168.0.7
          ansible_user: root
          connectx: true
          zfsiscsi: true
          linstor: true
          linstor_controller: true
          linstor_controller_priority: 100
          linstor_disks: false # make true later when it has the needed disks?
        Ennead:
          ansible_host: 192.168.0.8
          ansible_user: root
          connectx: true
          zfsiscsi: true
          linstor: true
          linstor_controller: true
          linstor_controller_priority: 200
          linstor_disks: true
          linstor_initial_controller: true
        Ogdoad:
          ansible_host: 192.168.0.9
          ansible_user: root
          connectx: true
          zfsiscsi: true
          linstor: true
          linstor_controller: true
      vars:
        vip_ip: 192.168.0.4
        linstor_pools:
          DfltStorPool:
            pool_name: DfltStorPool
            zfs_pool: essd
            placecount: 1
            resource_group_name: RG-DfltStorPool
          BulkPool:
            pool_name: BulkPool
            zfs_pool: hdd
            placecount: 1
            resource_group_name: RG-BulkPool
    ubuntu_vms:
      hosts:
        # AI Docker host
        Arnold:
          ansible_host: 192.168.0.71
          cmk_folder: '/LAN'
          docker_enabled: true
          Arnold: true
        # Main Docker host
        Beluga:
          ansible_host: 192.168.0.75
          cmk_folder: '/LAN'
          docker_enabled: true
          Beluga: true
    tdarr:
      hosts:
        TdarrServer:
          ansible_host: 192.168.0.80
          ansible_user: root
          tdarr_server: true
          tdarr_node: true
        TdarrNode01:
          ansible_host: 192.168.0.81
          ansible_user: root
          tdarr_node: true
        TdarrNode02:
          ansible_host: 192.168.0.82
          ansible_user: root
          tdarr_node: true
        TdarrNode03:
          ansible_host: 192.168.0.83
          ansible_user: root
          tdarr_node: true
