all:
  children:
    proxmox:
      hosts:
        Aesir:
          ansible_host: 192.168.0.5
          cmk_folder: '/LAN'
          connectx: true
          intel_sriov: true
          zfsiscsi: true
          linstor: true
          linstor_controller: true
          linstor_controller_priority: 100
        Vanir:
          ansible_host: 192.168.0.6
          cmk_folder: '/LAN'
          connectx: true
          zfsiscsi: true
          linstor: true
          linstor_controller: true
    ubuntu_vms:
      hosts:
        # AI Docker host
        Arnold:
          ansible_host: 192.168.0.71
          cmk_folder: '/LAN'
          docker_enabled: true
          Arnold: true
        # Main Docker host
        Beluga:
          ansible_host: 192.168.0.75
          cmk_folder: '/LAN'
          docker_enabled: true
          Beluga: true
