all:
  children:
    proxmox:
      hosts:
        Aesir:
          ansible_host: 192.168.0.5
          ansible_user: root
          connectx: true
          intel_sriov: true
          zfsiscsi: true
          linstor: true
        Vanir:
          ansible_host: 192.168.0.6
          ansible_user: root
          connectx: true
          zfsiscsi: true
          linstor: true
        Olympian:
          ansible_host: 192.168.0.7
          ansible_user: root
          connectx: true
          linstor: true
          linstor_controller: true
          linstor_controller_priority: 200
          linstor_disks: true
        Ennead:
          ansible_host: 192.168.0.8
          ansible_user: root
          connectx: true
          linstor: true
          linstor_controller: true
          linstor_controller_priority: 100
          linstor_disks: true
          linstor_initial_controller: true
    ubuntu_vms:
      hosts:
        # AI Docker host
        Arnold:
          ansible_host: 192.168.0.71
          cmk_folder: '/LAN'
          docker_enabled: true
          Arnold: true
        # Main Docker host
        Beluga:
          ansible_host: 192.168.0.75
          cmk_folder: '/LAN'
          docker_enabled: true
          Beluga: true
    tdarr:
      hosts:
        tdarr_server:
          ansible_host: 192.168.0.80
          tdarr_server: true
          tdarr_node: true
        tdarr_node01:
          ansible_host: 192.168.0.81
          tdarr_node: true
        tdarr_node02:
          ansible_host: 192.168.0.82
          tdarr_node: true
        tdarr_node03:
          ansible_host: 192.168.0.83
          tdarr_node: true
        tdarr_node04:
          ansible_host: 192.168.0.84
          tdarr_node: true
