services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=America/Toronto
    volumes:
      - lutris_data:/config
    ports:
      - 10002:80
    restart: unless-stopped
volumes:
  lutris_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ NAS_IP }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Zoom/docker/lutris_data"