---
services:
  radarr:
    image: hotio/radarr:latest
    container_name: radarr
    environment:
      - UMASK=007
    volumes:
      - radarr_data:/config
      - media:/Media
      - downloads:/Downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    container_name: sonarr
    image: hotio/sonarr:latest
    ports:
      - "8989:8989"
    environment:
      - UMASK=007
    volumes:
      - sonarr_data:/config
      - media:/Media
      - downloads:/Downloads
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    environment:
      - BASE_URL=/ombi
    volumes:
      - ombi_data:/config
    ports:
      - 3579:3579
    restart: unless-stopped
  maintainerr:
    image: jorenn92/maintainerr:latest
    container_name: maintainerr
    volumes:
      - maintainerr_data:/opt/data
    environment:
      - TZ=America/Toronto
#     - DEBUG=true # uncomment to enable debug logs
    ports:
      - 6246:6246
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - TZ=America/Toronto
    volumes:
      - bazarr_data:/config
      - media:/Media
    ports:
      - 6767:6767
    restart: unless-stopped
  autoscan:
    container_name: autoscan
    image: hotio/autoscan:latest
    ports:
      - "3030:3030"
    volumes:
      - autoscan_data:/config
    restart: unless-stopped
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=America/Toronto
      - serverIP={{ ci_ipv4_address }} 
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
      - inContainer=true
      - ffmpegVersion=6
    volumes:
      - tdarr_server_data:/app
      - media:/Media
    # For use with systems with intel igpu sr-iov enabled
    #devices:
    #  - /dev/dri:/dev/dri
  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - tautulli_data:/config
    environment:
      - TZ=America/Toronto
    ports:
      - 8181:8181
volumes:
  radarr_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ docker.nas_ip }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Zoom/docker/radarr_data"
  sonarr_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ docker.nas_ip }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Zoom/docker/sonarr_data"
  media:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ docker.nas_ip }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Mass/Media"
  downloads:
    driver: local
    driver_opts:
      type: cifs
      o: "username={{ docker.cifs_downloads_username }},password={{ docker.cifs_downloads_password }},uid=1000,gid=1000,dir_mode=0775" 
      device: '//{{ docker.cifs_downloads_ip }}/z'
  ombi_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ docker.nas_ip }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Zoom/docker/ombi_data"
  maintainerr_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ docker.nas_ip }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Zoom/docker/maintainerr_data"
  bazarr_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ docker.nas_ip }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Zoom/docker/bazarr_data"
  tdarr_server_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ docker.nas_ip }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Zoom/docker/tdarr_server_data"
  tautulli_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ docker.nas_ip }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Zoom/docker/tautulli_data"
  autoscan_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ docker.nas_ip }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Zoom/docker/autoscan_data"