---
- name: Ensure Checkmk Agent is Installed
  hosts: all
  become: true
  vars_files:
    - vars/cmkvault.yml
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: apt
    - name: Copy somefile.conf from role's files directory
      ansible.builtin.copy:
        src: files/check-mk-agent_2.3.0p9-1_all.deb  # Ansible automatically looks inside the role's files/
        dest: /tmp/check-mk-agent_2.3.0p9-1_all.deb
        owner: root
        group: root
        mode: '0644'
      when: "'check_mk_agent' not in ansible_facts.packages"

    - name: Install the .deb package using dpkg
      ansible.builtin.dpkg_selections:
        name: "{{ deb_package_dest }}"
        selection: install
      register: dpkg_result
      when: "'check_mk_agent' not in ansible_facts.packages"
    - name: Register CMK agent
      ansible.builtin.shell: >
        cmk-agent-ctl register
        --hostname {{ inventory_hostname }}
        --server 192.168.0.68
        --site monitoring
        --user '{{ cmk_user }}'
        --password '{{ cmk_password }}'
      args:
        executable: /bin/bash
      no_log: true
      when: "'check_mk_agent' not in ansible_facts.packages"
      changed_when: false
