#I live in /etc/drbd-reactor.d/linstor_db.toml
[[promoter]]
id = "linstor_db"
resource = "linstor_db"
# Maximum priority for the node
node-max-priority = true

# Define individual node priorities
[[promoter.node-priority]]
name = "pve1"
priority = 100

[[promoter.node-priority]]
name = "pve2"
priority = 50

[[promoter.node-priority]]
name = "pve3"
priority = 10

[promoter.resources.linstor_db]
start = ["var-lib-linstor.mount", "linstor-controller.service", "linstor-gateway.service"]
stop = ["var-lib-linstor.mount", "linstor-controller.service", "linstor-gateway.service"]
on-stop-failure = "demote"  # Possible values: "ignore", "stop", "demote"
stop-services-on-exit = true  # Ensures services are stopped when the promoter exits

#Ensures that the db follows the nfs mount as the nfs mount uses the vip configured in here. 
#The soft dependancy ensures theres no issues on fresh cluster start as the nfs service needs the db service started somewhere to actually start
[[promoter.resource-dependencies]]
resource = "linstor-gateway-nfs-nfs"
type = "soft"
