---
- name: Run all the required tasks to add a new node to linstor
  hosts: all
  become: yes
  tasks:
#Still a WIP, dont use
#Installing linstor public repos as per the folliwng documentation
#https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-proxmox-ls-install    
    - name: Download Linstor Public Repo Key
      get_url:
        url: "https://packages.linbit.com/package-signing-pubkey.asc"
        dest: /tmp/package-signing-pubkey.asc
        mode: '0755'

    - name: Import Linstor Repo key
      environment:
        TERM: xterm
      command: "gpg --yes -o /etc/apt/trusted.gpg.d/linbit-keyring.gpg --dearmor /tmp/package-signing-pubkey.asc"        
    
    - name: Overwrite linbit.list with LINBIT repository entry
      copy:
        content: |
          deb [signed-by=/etc/apt/trusted.gpg.d/linbit-keyring.gpg] http://packages.linbit.com/public/ proxmox-8 drbd-9
        dest: /etc/apt/sources.list.d/linbit.list
        owner: root
        group: root
        mode: '0644'
#Update apt cache with our nice new repo
    - name: Update apt cache
      apt:
        update_cache: yes
#Create mount service for linstor database in case this node ever become active
#As per https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-linstor_ha
    - name: Create var-lib-linstor.mount file
      copy:
        content: |
          [Unit]
          Description=Filesystem for the LINSTOR controller

          [Mount]
          # you can use the minor like /dev/drbdX or the udev symlink
          What=/dev/drbd/by-res/linstor_db/0
          Where=/var/lib/linstor
        dest: /etc/systemd/system/var-lib-linstor.mount
        owner: root
        group: root
        mode: '0644'
   
    - name: Create /var/lib/linstor directory
      file:
        path: /var/lib/linstor
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Set immutable attribute on /var/lib/linstor
      command: chattr +i /var/lib/linstor
#Create required directories and pull down configuration files from github
    - name: Create /etc/linstor directory
      file:
        path: /etc/linstor
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create /etc/drbd-reactor.d directory
      file:
        path: /etc/drbd-reactor.d
        state: directory
        owner: root
        group: root
        mode: '0755'       

    - name: Create /etc/systemd/system/linstor-satellite.service.d/ directory
      file:
        path: /etc/systemd/system/linstor-satellite.service.d/
        state: directory
        owner: root
        group: root
        mode: '0755'    
    
    - name: Download linstor-client.conf
      get_url: 
        url: "https://raw.githubusercontent.com/RumenBlack84/ansible/main/linstor-configs/linstor-client.conf"
        dest: /etc/linstor/linstor-client.conf
        mode: '0755'
    
    - name: Download linstor_db.toml
      get_url: 
        url: "https://raw.githubusercontent.com/RumenBlack84/ansible/main/linstor-configs/linstor_db.toml"
        dest: /etc/drbd-reactor.d/linstor_db.toml
        mode: '0755'
    
    - name: Download override.conf
      get_url: 
        url: "https://raw.githubusercontent.com/RumenBlack84/ansible/main/linstor-configs/override.conf"
        dest: /etc/systemd/system/linstor-satellite.service.d/override.conf
        mode: '0755'      
    
    - name: Download linstor-gateway-nfs-nfs.toml
      get_url: 
        url: "https://raw.githubusercontent.com/RumenBlack84/ansible/main/linstor-configs/linstor-gateway-nfs-nfs.toml"
        dest: /etc/drbd-reactor.d/linstor-gateway-nfs-nfs.toml
        mode: '0755'            
#Install required linstor Packages
    - name: Install drbd-dkms
      apt:
        name: drbd-dkms
        state: present
    - name: Install drbd-utils
      apt:
        name: drbd-utils
        state: present
    - name: Install linstor-controller
      apt:
        name: linstor-controller
        state: present
    - name: Install linstor-satellite
      apt:
        name: linstor-satellite
        state: present
    - name: Install linstor-client
      apt:
        name: linstor-client
        state: present
    - name: Install linstor-proxmox
      apt:
        name: linstor-proxmox
        state: present
    - name: Install drbd-reactor
      apt:
        name: drbd-reactor
        state: present
#Install Dependancies for building linstor-gateway        
    - name: Ensure Go is installed
      apt:
        name: golang
        state: present
        update_cache: yes
    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes        
#install linstor gateway
    - name: Clone the repository
      git:
        repo: 'https://github.com/LINBIT/linstor-gateway'
        dest: /tmp/linstor-gateway

    - name: Build the linstor-gateway package
      shell: |
        cd /tmp/linstor-gateway
        make
      args:
        chdir: /tmp/linstor-gateway
    - name: Move the binary to /usr/bin
      copy:
        src: /tmp/linstor-gateway/linstor-gateway
        dest: /usr/bin/linstor-gateway
        mode: '0755'
    - name: Verify the binary is built and in /usr/bin
      stat:
        path: /usr/bin/linstor-gateway
      register: linstor_gateway_stat

    - name: Debug output of binary existence
      debug:
        msg: "linstor-gateway binary exists at /usr/bin/linstor-gateway: {{ linstor_gateway_stat.stat.exists }}"
#Enable and start required systemd services
    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start linstor-satellite service
      systemd:
        name: linstor-satellite
        enabled: yes
        state: started

    - name: Enable and start drbd-reactor service
      systemd:
        name: drbd-reactor
        enabled: yes
        state: started        
#    - name: 
#      apt:
#        name: 
#        state: present
        
