---
- name: Run Proxmox VE Post Install Script
  hosts: all
  become: yes
  tasks:
    - name: Download the Proxmox VE post install script
      get_url:
        url: https://raw.githubusercontent.com/RumenBlack84/ansible/main/bash%20scripts/proxmox/unattended-pve-post-install.sh
        dest: /tmp/unattended-pve-post-install.sh
        mode: '0755'

    - name: Run the Proxmox VE post install script with arguments
      environment:
        TERM: xterm
      command: "bash /tmp/unattended-pve-post-install.sh -y -s -e -c -p -u"
      args:
        creates: /tmp/unattended-pve-post-install.sh.completed

    - name: Mark script as completed
      file:
        path: /tmp/unattended-pve-post-install.sh.completed
        state: touch
    # Installing and pinning Kernel to 6.5.13-3-pve so as to not break intel igpu sr-iov on pve1 & pve2
    - name: Install specific kernel version
      apt:
        name: pve-kernel-6.5.13-3-pve
        state: present
        update_cache: yes

    - name: Install specific kernel headers
      apt:
        name: pve-headers-6.5.13-3-pve
        state: present
        update_cache: yes

    - name: Hold specific kernel version
      command: "apt-mark hold proxmox-kernel-6.5.13-3-pve"

    - name: Hold pve-kernel package
      command: "apt-mark hold proxmox-default-kernel"

    - name: Pin specific kernel version in Proxmox
      shell: "yes | proxmox-boot-tool kernel pin 6.5.13-3-pve"   
      
    # Changing bootloader to use grub instead of systemd
    - name: Find EFI partitions
      command: blkid -t TYPE=vfat -o device
      register: efi_partition_output

    - name: Set EFI partitions as a list
      set_fact:
        efi_partitions: "{{ efi_partition_output.stdout_lines }}"

    - name: Set Grub kernel parameters to enable IOMMU
      command: "sed -i '/^GRUB_CMDLINE_LINUX_DEFAULT/c\\GRUB_CMDLINE_LINUX_DEFAULT=\"quiet intel_iommu=on iommu=pt\"' /etc/default/grub"

    - name: Initialize Proxmox boot tool on each EFI partition
      command: "proxmox-boot-tool init {{ item }} grub"
      loop: "{{ efi_partitions }}"
      when: efi_partitions is defined

    - name: Print EFI partitions for verification
      debug:
        msg: "EFI partitions: {{ efi_partitions }}"

    - name: Refresh Boot
      command: "proxmox-boot-tool refresh"
