---
- name: Run Proxmox VE Post Install Script  
  hosts: all
  tasks:
    - name: Download the Proxmox VE post install script
      get_url:
        url: https://raw.githubusercontent.com/RumenBlack84/ansible/main/bash%20scripts/proxmox/unattended-pve-post-install.sh
        dest: /tmp/unattended-pve-post-install.sh
        mode: '0755'

    - name: Run the Proxmox VE post install script with arguments
      environment:
        TERM: xterm
      command: "bash /tmp/unattended-pve-post-install.sh -y -s -e -c -p -u"
      args:
        creates: /tmp/unattended-pve-post-install.sh.completed

    - name: Mark script as completed
      file:
        path: /tmp/unattended-pve-post-install.sh.completed
        state: touch
#Installing linstor public repos as per the folliwng documentation
#https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-proxmox-ls-install    
    - name: Download Linstor Public Repo Key
      get_url:
        url: https://packages.linbit.com/package-signing-pubkey.asc"
        dest: /tmp/package-signing-pubkey.asc
        mode: '0755'

    - name: Import Linstor Repo key
      environment:
        TERM: xterm
      command: "gpg --yes -o /etc/apt/trusted.gpg.d/linbit-keyring.gpg --dearmor /tmp/package-signing-pubkey.asc"        

    - name: Add Linstor Repo for PVE Version 8
      environment:
        TERM: xterm
      command: "PVERS=8 && echo "deb [signed-by=/etc/apt/trusted.gpg.d/linbit-keyring.gpg] http://packages.linbit.com/public/ proxmox-$PVERS drbd-9" > /etc/apt/sources.list.d/linbit.list"
#changing bootloader to use grub instead of systemd
#Installing and pinning Kernel to 6.5.13-3-pve so as to not break intel igpu sr-iov on pve1 & pve2
