---
- name: Run Proxmox VE Post Install Process
  hosts: all
  become: true
  vars:
    ansible_shell_executable: /bin/bash  # Use bash as the default shell
  tasks:
# Duplicate Promox helper script functions
# Correct VE sources
    - name: Correcting Proxmox VE Sources
      block:
        - name: Update sources.list
          ansible.builtin.copy:
            content: |
              deb http://deb.debian.org/debian bookworm main contrib
              deb http://deb.debian.org/debian bookworm-updates main contrib
              deb http://security.debian.org/debian-security bookworm-security main contrib
            dest: /etc/apt/sources.list
            owner: root
            group: root
            mode: '0644'

        - name: Add non-free firmware configuration
          ansible.builtin.copy:
            content: |
              APT::Get::Update::SourceListWarnings::NonFreeFirmware "false";
            dest: /etc/apt/apt.conf.d/no-bookworm-firmware.conf
            owner: root
            group: root
            mode: '0644'
    # Disable enterprise repos
    - name: Ensure pve-enterprise repository is disabled
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: '^deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
        line: '# deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
        mode: "0644"
        create: true
    # Enable free no sub repo
    - name: Enable 'pve-no-subscription' repository
      ansible.builtin.copy:
        content: |
          deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
        dest: /etc/apt/sources.list.d/pve-install-repo.list
        owner: root
        group: root
        mode: '0644'
    # Fix the ceph repos
    - name: Correcting 'ceph package repositories'
      ansible.builtin.copy:
        content: |
          # deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
          # deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
          # deb https://enterprise.proxmox.com/debian/ceph-reef bookworm enterprise
          # deb http://download.proxmox.com/debian/ceph-reef bookworm no-subscription
        dest: /etc/apt/sources.list.d/ceph.list
        owner: root
        group: root
        mode: '0644'
    # Remove Subscription Nag
    - name: Copy no-nag-script to the target machine
      ansible.builtin.copy:
        src: files/no-nag-script  # Path to the file on the Ansible host
        dest: /etc/apt/apt.conf.d/no-nag-script  # Path where it will be copied on the target
        owner: root
        group: root
        mode: '0644'

    - name: Reinstall proxmox-widget-toolkit  # noqa command-instead-of-module
      ansible.builtin.command: apt-get install --reinstall -y proxmox-widget-toolkit
      register: reinstall_result
      changed_when: reinstall_result.rc == 0

    # Update now that repos are fixed
    - name: Upgrade all packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
    # Installing and pinning Kernel to 6.8.12-1-pve so as to not break intel igpu sr-iov
    - name: Install specific kernel version
      ansible.builtin.apt:
        name: pve-kernel-6.8.12-1-pve
        state: present
        update_cache: true

    - name: Install specific kernel headers
      ansible.builtin.apt:
        name: pve-headers-6.8.12-1-pve
        state: present
        update_cache: true

    - name: Check if proxmox-kernel is already on hold
      ansible.builtin.shell: "set -o pipefail && apt-mark showhold | grep -q proxmox-kernel-6.8.12-1-pve"
      register: kernel_on_hold
      failed_when: kernel_on_hold.rc > 1
      changed_when: false

    - name: Hold specific kernel version
      ansible.builtin.command: "apt-mark hold proxmox-kernel-6.8.12-1-pve"
      when: kernel_on_hold.rc != 0
      changed_when: true

    - name: Check if proxmox-headers are already on hold
      ansible.builtin.shell: "set -o pipefail && apt-mark showhold | grep -q proxmox-headers-6.8.12-1-pve"
      register: header_on_hold
      failed_when: header_on_hold.rc > 1
      changed_when: false

    - name: Hold kernel headers
      ansible.builtin.command: "apt-mark hold proxmox-headers-6.8.12-1-pve"
      when: header_on_hold.rc != 0
      changed_when: true

    - name: Get pinned kernel version
      ansible.builtin.shell: "set -o pipefail && proxmox-boot-tool kernel list | awk '/Pinned kernel:/{getline; print}'"
      register: pinned_kernel
      changed_when: false
      failed_when: pinned_kernel.rc > 1

    - name: Unpin the current kernel if it doesn't match the desired one
      ansible.builtin.command: "proxmox-boot-tool kernel unpin"
      when: pinned_kernel.stdout != '' and pinned_kernel.stdout != '6.8.12-1-pve'
      changed_when: true

    - name: Pin specific kernel version in Proxmox
      ansible.builtin.shell: "set -o pipefail && yes | proxmox-boot-tool kernel pin 6.8.12-1-pve"
      when: pinned_kernel.stdout != '6.8.12-1-pve'
      # Ignore rc 141 sigpipe since we are just using it to pass yes to the kernel pin command for automation
      failed_when: pinned_kernel.rc != 0 and pinned_kernel.rc != 141
      changed_when: true

    - name: Set Grub kernel parameters
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=.*'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"'
        backup: true

    # Changing bootloader to use grub instead of systemd
    - name: Find EFI partitions
      ansible.builtin.command: blkid -t TYPE=vfat -o device
      register: efi_partition_output
      changed_when: false

    - name: Set EFI partitions as a list
      ansible.builtin.set_fact:
        efi_partitions: "{{ efi_partition_output.stdout_lines }}"

    - name: Initialize Proxmox boot tool on each EFI partition
      ansible.builtin.command: "proxmox-boot-tool init {{ item }} grub"
      loop: "{{ efi_partitions }}"
      when: efi_partitions is defined
      register: proxmox_boot_init
      changed_when: proxmox_boot_init.rc == 0 and "nothing to do" not in proxmox_boot_init.stdout

    - name: Print EFI partitions for verification
      ansible.builtin.debug:
        msg: "EFI partitions: {{ efi_partitions }}"

    - name: Refresh Boot
      ansible.builtin.command: "proxmox-boot-tool refresh"
      register: proxmox_boot_refresh
      changed_when: proxmox_boot_refresh.rc == 0 and "no changes" not in proxmox_boot_refresh.stdout
