services:
  protonmail-bridge:
    image: shenxn/protonmail-bridge
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - protonmail_data:/root
volumes:
  protonmail_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr={{ NAS_IP }},rw,nfsvers=4.2,nconnect=8"
      device: ":/mnt/Zoom/docker/protonmail_data"
